### ISSUE TITLE
Exactly one occurrence rule grab many occurrences

### ISSUE THREAD

**Issue by Songbird0** [pest-parser/pest#155]
Hi!

After [this](https://github.com/pest-parser/pest/issues/154), I created these rules:

```rust
delimiter_run_star = @{ "*"+ ~ !"*" ~ character } // matches exactly one `character`
delimiter_run_us = @{ "_"+ ~ !"_" ~ character } // matches exactly one `character`
...
// Character specifications

// Matches exactly one character from this list:
character = @{ uppercase_letter | lowercase_letter | accent | punctuation }
digit = { '0'..'9' }
uppercase_letter = { 'A'..'Z' }
lowercase_letter = { 'a'..'z' }
accent = { "¡" | "¢" | "£" | "¤" | "¥" | "¦" | "§" | "¨" | "©" | "ª" | "«" | "¬" | "­" | "®" | "¯" | "°" | "±" | "²" | "³" | "´" | "µ" | "¶" | "·" | "¸" | "¹" | "º" | "»" | "¼" | "½" | "¾" | "¿" | "À" | "Á" | "Â" | "Ã" | "Ä" | "Å" | "Æ" | "Ç" | "È" | "É" | "Ê" | "Ë" | "Ì" | "Í" | "Î" | "Ï" | "Ð" | "Ñ" | "Ò" | "Ó" | "Ô" | "Õ" | "Ö" | "×" | "Ø" | "Ù" | "Ú" | "Û" | "Ü" | "Ý" | "Þ" | "ß" | "à" | "á" | "â" | "ã" | "ä" | "å" | "æ" | "ç" | "è" | "é" | "ê" | "ë" | "ì" | "í" | "î" | "ï" | "ð" | "ñ" | "ò" | "ó" | "ô" | "õ" | "ö" | "÷" | "ø" | "ù" | "ú" | "û" | "ü" | "ý" | "þ" | "ÿ" }
punctuation = { "!" | "\"" | "#" | "$" | "%" | "&" | "'" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "\\" | "]" | "^" | "_" | "`" | "{" | "|" | "}" | "~" | "" }
whitespace = _{ " " }
```

Successful unit tests:

```rust
#[test]
fn delimiter_run_star9() {
    parses_to! {
        parser: MarkdownParser,
        input: "*abc", // matches `*a` (0, 2)
        rule: Rule::delimiter_run_star,
        tokens: [
            delimiter_run_star(0, 2)
        ]
    }
}

#[test]
fn delimiter_run_us9() {
    parses_to! {
        parser: MarkdownParser,
        input: "_abc", // matches `_a` (0, 2)
        rule: Rule::delimiter_run_us,
        tokens: [
            delimiter_run_us(0, 2)
        ]
    }
}
```

Unsuccessful unit tests:

```rust
#[test]
fn delimiter_run_star8() {
    parses_to! {
        parser: MarkdownParser,
        input: "*******¡foo bar", // matches `*******¡f` (0, 9) instead of (0, 8)
        rule: Rule::delimiter_run_star,
        tokens: [
            delimiter_run_star(0, 8)
        ]
    }
}

#[test]
fn delimiter_run_us8() {
    parses_to! {
        parser: MarkdownParser,
        input: "_______¡foo bar",  // matches `_______¡f` (0, 9) instead of (0, 8)
        rule: Rule::delimiter_run_us,
        tokens: [
            delimiter_run_us(0, 8)
        ]
    }
}

#[test]
fn delimiter_run_star10() {
    parses_to! {
        parser: MarkdownParser,
        input: "*¡abc", // matches `*¡a` (0, 3) instead of (0, 2)
        rule: Rule::delimiter_run_star,
        tokens: [
            delimiter_run_star(0, 2)
        ]
    }
}

#[test]
fn delimiter_run_us10() {
    parses_to! {
        parser: MarkdownParser,
        input: "_¡abc", // matches `_¡a` (0, 3) instead of (0, 2)
        rule: Rule::delimiter_run_us,
        tokens: [
            delimiter_run_us(0, 2)
        ]
    }
}
```
`¡` character is a part of `accent` rule/list itself is a part of `character` rule/list, so where is my error?

The parser is backtracking to grab (why?) additional characters coming from different lists (it seems to do this, at least).

## Meta

You would like to check the errors, maybe, so here are the associated errors:

```rust
---- delimiter_run_star10 stdout ----
        thread 'delimiter_run_star10' panicked at 'expected End { rule: delimiter_run_star, pos: Position { pos: 2 } } but found End { rule: delimiter_run_star, pos: Position { 3 } }', tests/markdown.rs:297
```
```rust
---- delimiter_run_us10 stdout ----
        thread 'delimiter_run_us10' panicked at 'expected End { rule: delimiter_run_us, pos: Position { pos: 2 } } but found End { rule: delimiter_run_us, pos: Position { 3 } }', tests/markdown.rs:309
```
```rust
---- delimiter_run_star8 stdout ----
        thread 'delimiter_run_star8' panicked at 'expected End { rule: delimiter_run_star, pos: Position { pos: 8 } } but found End { rule: delimiter_run_star, pos: Position { 9 } }', tests/markdown.rs:249
```
```rust
---- delimiter_run_us8 stdout ----
        thread 'delimiter_run_us8' panicked at 'expected End { rule: delimiter_run_us, pos: Position { pos: 8 } } but found End { rule: delimiter_run_us, pos: Position { 9 } }', tests/markdown.rs:261
```

Thanks for help.

**Comment by dragostis** [comment]
It's not grabbing additional characters. The `'¡'` character simply occupies 2 bytes instead of one, which is exactly why you're getting the error. All position information in pest is in bytes.

**Comment by Songbird0** [comment]
*Note this somewhere in his mind*

Ok, thanks!
