### ISSUE TITLE
Not compiling on nightly-msvc

### ISSUE THREAD

**Issue by CGMossa** [pest-parser/pest#525]
This crate is not compiling using `nightly-msvc`. I'm seeing this issue as part of compiling rocket.

```
error: linking with `link.exe` failed: exit code: 1120


error: aborting due to previous error

error: could not compile `pest_derive`

Caused by:
```

**Comment by CGMossa** [comment]
I've found that the problem is with ``error: could not compile `pest_bootstrap``.

**Comment by CGMossa** [comment]
On `stable-msvc` I get this message:

```
[pest_meta 2.1.3] rerun-if-changed=src/grammar.pest
[pest_meta 2.1.3] Bootstrapping `meta/src/grammar.rs`
[pest_meta 2.1.3] thread 'main' panicked at 'Bootstrap failed because no bootstrap executable was found. Please run `cargo build --package pest_bootstrap` or `cargo bootstrap` and then try again.', meta\build.rs:52:21
[pest_meta 2.1.3] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `pest_meta v2.1.3 (C:\Users\tpb398\Documents\GitHub\pest\meta)`

Caused by:
  process didn't exit successfully: `C:/cargo_target_dir\debug\build\pest_meta-ec990508d96736e6\build-script-build` (exit code: 101)
  --- stdout
  rerun-if-changed=src/grammar.pest
  Bootstrapping `meta/src/grammar.rs`

  --- stderr
  thread 'main' panicked at 'Bootstrap failed because no bootstrap executable was found. Please run `cargo build --package pest_bootstrap` or `cargo bootstrap` and then try again.', meta\build.rs:52:21
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by CGMossa** [comment]
All of a sudden it works: The "regular" linker results in a miscompilation if `rustflags = ["-Ctarget-cpu=native"]`. 
I've added 
```toml

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
```

This seems to solve all the problems.

How and where do I report / fix this?
